### ISSUE TITLE
ZzUncompressBlock does not work

### ISSUE THREAD

**Issue by Behrouz-m** [ddebin/zzip#1]
I tried to use it but it failed on **ZzUncompressBlock**. I attached the zzlib source code to my project to detect the location of error. The error is in **struct_mode1.c** file:

``` c++

/* Start the model (init) sub-function */
static
void Start_Model_2(s_SM1_i *t_i, 
                       s_SM1_f *t_f)
{
    uint i;

    for (i = 0; i < t_f[0].freq; ++i)
    {
        t_i[i].char_to_index = i + 1;
        t_i[i + 1].index_to_char = i;
    }

    t_f[0].cum = t_f[0].freq;
    for (i = 1; i <= t_f[0].freq; ++i)
    {
        t_f[i].freq = 1;          // << This line produce segmentation fault error.
        t_f[i].cum = t_f[0].freq - i;
    }
}

```

I'm building the project with MinGw32 , GCC 4.9.3 32bit, Windows 10 x64

**Comment by ray-pixar** [comment]
I'm going to use this lib to my project seriously. If there is a quick fix I appreciate it.

**Comment by Behrouz-m** [comment]
It was my fault! Now it works. thanks for the lib.
